### ISSUE TITLE
I'm not able to properly configure LDAP access

### ISSUE THREAD

**Issue by luizjr** [dignajar/another-ldap#4]
I'm not able to properly configure LDAP access
It always returns connection error
![image](https://user-images.githubusercontent.com/1474563/153151477-f5b4fe12-865c-4479-b272-114656701563.png)

**Comment by dignajar** [comment]
Looks like the username or password is incorrect is not about connection error.

The finalUsername displayed in the logs has the correct structure for your LDAP server ? have you tried with `ldapsearch` ?

**Comment by luizjr** [comment]
I don't know, I've tried several ways but none establish a connection.
![image](https://user-images.githubusercontent.com/1474563/153164998-35204045-1a66-4529-ab90-dcf70c0a9484.png)

**Comment by glebrodionov94** [comment]
hi! somthing wrong?
![image](https://user-images.githubusercontent.com/94922743/153901913-7f8e0f97-ed43-4cc5-9767-cd7d341d4c87.png)
![image](https://user-images.githubusercontent.com/94922743/153901976-722d1bab-c57c-41a6-997f-8a1cd26e6b1c.png)
![image](https://user-images.githubusercontent.com/94922743/153902510-fe4e49a1-17ad-4d3f-9097-a0fe75cca549.png)

**Comment by luizjr** [comment]
> hi! somthing wrong? ![image](https://user-images.githubusercontent.com/94922743/153901913-7f8e0f97-ed43-4cc5-9767-cd7d341d4c87.png) ![image](https://user-images.githubusercontent.com/94922743/153901976-722d1bab-c57c-41a6-997f-8a1cd26e6b1c.png) ![image](https://user-images.githubusercontent.com/94922743/153902510-fe4e49a1-17ad-4d3f-9097-a0fe75cca549.png)

Now I'm having the same problem!

![image](https://user-images.githubusercontent.com/1474563/153922816-7a1b8a60-d812-4fbb-bc1c-8e13c4d18e52.png)

**Comment by glebrodionov94** [comment]
> > Привет! что-то не так?![изображение](https://user-images.githubusercontent.com/94922743/153901913-7f8e0f97-ed43-4cc5-9767-cd7d341d4c87.png) ![изображение](https://user-images.githubusercontent.com/94922743/153901976-722d1bab-c57c-41a6-997f-8a1cd26e6b1c.png) ![изображение](https://user-images.githubusercontent.com/94922743/153902510-fe4e49a1-17ad-4d3f-9097-a0fe75cca549.png)
> 
> Теперь у меня такая же проблема!
> 
> ![изображение](https://user-images.githubusercontent.com/1474563/153922816-7a1b8a60-d812-4fbb-bc1c-8e13c4d18e52.png)

add configmap COOKIE_DOMAIN: .example.com

**Comment by dignajar** [comment]
can you paste all your Kubernetes manifests ?

**Comment by yuyangood** [comment]
I'm having the same problem!

deployment.yaml
`---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: another-ldap
  namespace: ops
  labels:
    app: another-ldap
spec:
  replicas: 1
  selector:
    matchLabels:
      app: another-ldap
  template:
    metadata:
      labels:
        app: another-ldap
    spec:
      automountServiceAccountToken: false
      containers:
        - name: another-ldap
          image: swr.cn-east-3.myhuaweicloud.com/wlyc-common/another-ldap:v0.9
          imagePullPolicy: Always
          ports:
            - name: https
              containerPort: 9000
          envFrom:
            - configMapRef:
                name: another-ldap
            - secretRef:
                name: another-ldap
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
          securityContext:
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            runAsUser: 10001
            capabilities:
              drop:
                - ALL
          livenessProbe:
            httpGet:
              port: 9000
              path: /
              scheme: HTTPS
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
            timeoutSeconds: 1
          readinessProbe:
            httpGet:
              port: 9000
              path: /
              scheme: HTTPS
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
            timeoutSeconds: 1
          volumeMounts:
            - name: vol-tmp
              mountPath: /tmp
      imagePullSecrets:
      - name: hw-swr-auth
      volumes:
        - name: vol-tmp
          emptyDir: {}`

ingress.yaml
`---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: ops
  name: another-ldap
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
spec:
  tls:
    - hosts:
        - another-ldap.50yc.com
      secretName: 50yc.com
  rules:
  - host: another-ldap.50yc.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: another-ldap
            port:
              number: 443`

secret.yaml
`---
apiVersion: v1
kind: Secret
metadata:
  name: another-ldap
  namespace: ops
type: Opaque
data:
  LDAP_MANAGER_PASSWORD: xxxxxxxxxx
  FLASK_SECRET_KEY: xxxxxxxxxx`

service.yaml
`kind: Service
apiVersion: v1
metadata:
  name: another-ldap
  namespace: ops
spec:
  type: ClusterIP
  selector:
    app: another-ldap
  ports:
    - name: https
      port: 443
      protocol: TCP
      targetPort: 9000`

configMap.yaml
`--
apiVersion: v1
kind: ConfigMap
metadata:
  name: another-ldap
  namespace: ops
data:
  LDAP_ENDPOINT: "ldap://xxxxxxxx:21389"
  LDAP_MANAGER_DN_USERNAME: "CN=LdapUser,DC=wlyd,DC=local"
  LDAP_BIND_DN: "{username}@wlyd.local"
  LDAP_SEARCH_BASE: "DC=wlyd,DC=local"
  LDAP_SEARCH_FILTER: "(sAMAccountName={username})"
  LOG_LEVEL: "DEBUG"
  LOG_FORMAT: "JSON"
  BRUTE_FORCE_PROTECTION: "False"
  BRUTE_FORCE_EXPIRATION: "5"
  BRUTE_FORCE_FAILURES: "3"
  COOKIE_DOMAIN: ""
  METADATA_TITLE: "Another LDAP"
  METADATA_DESCRIPTION: ""
  METADATA_FOOTER: "Powered by Another LDAP"
  PERMANENT_SESSION_LIFETIME: "7"`


app-ingress.yaml
![image](https://user-images.githubusercontent.com/20431543/154041389-74a18cc8-dcd5-4013-a614-89489210cfbd.png)

**Comment by glebrodionov94** [comment]
> > Вы можете вставить все свои манифесты Kubernetes?
> 
> У меня тоже такая же проблема!
> 
try to add configmap COOKIE_DOMAIN: .50yc.com

**Comment by dignajar** [comment]
Yes in all configurations you posted here is missing the environment `COOKIE_DOMAIN`.

To start with the troubleshooting, try to log in to the Login page, `another-ldap.50yc.com`.

**Comment by yuyangood** [comment]
> > > Вы можете вставить все свои манифесты Kubernetes?
> > 
> > 
> > У меня тоже такая же проблема!
> 
> try to add configmap COOKIE_DOMAIN: .50yc.com

Thank for you ask. Now I can login. Thank

**Comment by dignajar** [comment]
@luizjr you need to change this file https://github.com/dignajar/another-ldap/tree/main/files/static and re-build the docker image.

**Comment by luizjr** [comment]
> @luizjr you need to change this file https://github.com/dignajar/another-ldap/tree/main/files/static and re-build the docker image.

I made a pull request, and it still suggests another improvement, please check
